### ISSUE TITLE
Support for more SQLpackage arguments

### ISSUE THREAD

**Issue by ReinierKop** [DrJohnT/PublishDacPac#2]
(Great work on this repo!)

Currently, you only support the following arguments for publishing using `SQLpackage.exe` as per [this script](https://github.com/DrJohnT/PublishDacPac/blob/master/PublishDacPac/public/Publish-DacPac.ps1#L122): 

```
/Action:Publish
/SourceFile:$DacPacPath
/Profile:$DacPacUpdatedProfilePath
```

Our use case does not play perfect with the `profile.xml` since depending on the environment, we'll need some different settings. There can be tens of different environments, all with different SQLCMD variable requirements.

Have you thought about allowing these combinations of arguments ([source](https://gist.github.com/davoscollective/adf9b890984e51d8dee2))?

```
/Action:Publish
/SourceFile:$sourceFile
/TargetServerName:$targetServerName
/TargetDatabaseName:$targetDBname
/V:SQLCMDVariable1=$SQLCMDVariable1
/v:SQLCMDVariable2=$SQLCMDVariable2
```

I'll probably be implementing something close to this so if you're open to PRs and if you're not working on this already, I'll be glad to be of help.

**Comment by DrJohnT** [comment]
Thanks for your input.  You can already set the target server and database names.   Maybe my documentation is not clear, but the module changes the DAC Publish Profile and overwrites the server and database names therein.  This gives you much finer control because the DAC Publish Profile has so many options.

I would like to support SQLCMD Variables which I have done in previous projects.  However, my primary aim for this PowerShell module was to allow me to deliver a quality Azure DevOps extension, which I have published here: https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac

I will add support for SQLCMD Variables in the near future.  Will update this thread when I have

**Comment by ReinierKop** [comment]
I didn't realize the server and database are already overwritten by the module. That's great. Looking forward to the `SQLCMD` addition. 

Thanks for the quick reply

**Comment by DrJohnT** [comment]
I have now implemented this functionality.  
Note that the script updates the SQLCMD variables in the DAC Publish Profile, which is a far better way of handling SQLCMD Variables.

See the example in the documentation on https://github.com/DrJohnT/PublishDacPac/blob/master/docs/Publish-DacPac.md

Update your PublishDacPac PowerShell module to version 1.0.2.3202 available here:
https://www.powershellgallery.com/packages/PublishDacPac/

**Comment by DrJohnT** [comment]
I also fully documented the module.  The full documentation is accessible from the project home page. https://github.com/DrJohnT/PublishDacPac/ 

Enjoy!

**Comment by ReinierKop** [comment]
Thanks very much, I'll check it out!

**Comment by ColinSmit1967** [comment]
Looks like a great piece of work, is there a possibility of adding Authorization method, user login and password?

**Comment by DrJohnT** [comment]
@ColinSmit1967 I added SQL Server authentication in 1.1.x of my [PublishDacPac PowerShell module](https://www.powershellgallery.com/packages/PublishDacPac/) and also my Azure DevOps extension [Publish DACPAC using a DAC Publish Profile](https://marketplace.visualstudio.com/items?itemName=DrJohnExtensions.PublishDacPac)
